### ISSUE TITLE
Purple A11y list of tools

### ISSUE THREAD

**Issue by younglim** [raihan71/web-a11y-guide#1]
Thanks for your talk at CityJS.  Would love for you to check out Purple A11y, an open-source accessibility testing tool 😄

CLI (For Devs, DevOps)
https://github.com/GovTechSG/purple-a11y

Cypress/Playwright integration (For Quality Engineers, e2e)
https://github.com/GovTechSG/purple-a11y/blob/master/INTEGRATION.md

Desktop app (Everyone)
https://github.com/GovTechSG/purple-a11y-desktop

**Comment by raihan71** [comment]
hey nice man can we add those list to the repo

**Comment by raihan71** [comment]
thank you for sharing been added @younglim 🤩🎉
